version: "3.4"
services:
  db:
    image: monkey97/mysql-book-store
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    build: 
      context: .
      dockerfile: Dockerfile
    environment: 
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_USER: docker
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_DATABASE: book_store
    ports: 
      - "3306:3306"
    networks:
      - book-store-network
  book-store:
    image: monkey97/book-store
    restart: always
    build: ./BookStore
    working_dir: /BookStore
    environment: 
      TZ: America/Sao_Paulo
      SPRING_BOOT_ENVIROIMENT: Production
    volumes: 
      - ./BookStore:/BookStore
      - ~/.m2:/root/.m2
    ports: 
      - "8080:8080"
    command: mvn clean spring-boot:run
    links:
      - db
    depends_on: 
      - db
    networks:
      - book-store-network
networks:
    book-store-network:
        driver: bridge
